apiVersion: apps/v1
kind: Deployment

metadata:
  name: chatbot-backend
spec:
  selector:
    matchLabels:
      app: chatbot-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: chatbot-backend
    spec:
      containers:
        - name: chatbot-backend
          image: chatbot-backend
          ports:
            - containerPort: 3000
